export const FETCH_PRODUCTSUCCESS = "FETCH_PRODUCT";

export const FETCH_PRODUCTBEGIN = "FETCH_PRODUCTBEGIN";

export const FETCH_PRODUCTFAILURE = "FETCH_PRODUCTFAILURE";

export const SORT_PRODUCT = "SORT_PRODUCT";

export const PAGINATION_PRODUCT = "PAGINATION_PRODUCT";

export const GET_COUNTPRODUCTS = "GET_COUNTPRODUCTS";
